### ISSUE TITLE
How to install pytorch and tensorflow

### ISSUE THREAD

**Issue by lixiangparadise** [salesforce/decaNLP#39]
I have installed pytorch and tensorflow in python
However,when I run the comman 'docker build -t decanlp . && cd -', it would install the pytorch and tensorflow. Because of the network speed, it would be interuppted.
I don't know why I have installed the pytorch and tensorflow but it still needs to download and install it.

Thank you for your answer.

**Comment by bmccann** [comment]
Because the default way to use this project is to use Docker, if you build the docker image yourself, it will install tensorflow and pytorch. You should be able to skip the docker build command now, and instead just use bmccann/decanlp:cuda9_torch041 for the code on the master branch. If you don't have CUDA, then you can simply remove the cuda9_ from the docker image tag.
