### ISSUE TITLE
Some observations

### ISSUE THREAD

**Issue by BlackRedGold** [salesforce/decaNLP#8]
I would like to make a contribution to this nice project:

(1) You must not download the code as "zip" file. You have to do it by "git clone" (since ".git" folder is needed during training.)
(2) I did add something like "-v  .../runtime:/runtime/" to "nvidia-docker run .." so that (4 GB of) test data is not downloaded again and again when one runs the container.
(3) The description for parameter "--gpus DEVICE_ID"  seems a little vague. If you have a single GPU, set this to "--gpus 0".

Best wishes
BlackRedGold

**Comment by bmccann** [comment]
Thanks for the observations.

1) I hadn’t considered downloading the code as a .zip, but I can make the dependency on .git optional. Thanks for pointing out this use case. 

2) you should no longer need to do this on master because all mentions of runtime should be converted to decaNLP. Let me know if not. If you’ve already downloaded the data to some location called runtime, you can move the .data directory in runtime to decaNLP/ to line up with master. 

3) agreed. I’ll add some info to the readme and a better description in arguments.py

**Comment by bmccann** [comment]
97181e99e9a5a41798b0a9a49b8b5e24c9b2c343 should help with this.

1) You can now pass --no_commit if you don't want to have the dependency on .git
3) I changed the README examples to use `--gpu` instead of `--gpus`. The multi-gpu training is a WIP right now anyways, so might as well suggest that only single-gpu training is available in the examples for now.

Let me know if you think this covers your observations. If so, go ahead and close this issue. Feel free to  add more suggestions though!
